### ISSUE TITLE
Firefox autocompletes the Wi-Fi key with the login password

### ISSUE THREAD

**Issue by bochecha** [ideascube/ideascube#237]
I logged in the app, and told Firefox to remember my login/password.

Then, in the admin part, trying to connect to a new Wi-Fi network, I'm asked for the Wi-Fi passphrase (as it should).

Unfortunately, Firefox decides to autocomplete this field with the password for my user account.

Which is very unlikely to be the passphrase for the Wi-Fi network I'm connecting to.

I couldn't find any way to tell Firefox not to autocomplete like that.

Apparently, this is by design: https://bugzilla.mozilla.org/show_bug.cgi?id=956906

**Comment by yohanboniface** [comment]
@diox not sure the issue is clear for you without the context, but basically we have two situations were we use type=password inputs (one for login, one for connecting to a wifi network), and when a user allows firefox to register its credentials for the first, it also "autofills" the second with the saved values of the first, even if those are on two different pages and have different names.

That does not seem right to me. Does that makes sense for you, or do you have any hint how to workaround that by chance?

(PS: I'm not on IRC - 'cause I'm in Ethiopia, and the UNHCR blocks port 22 which prevents me to connect to my weechat… yeah I know I should have changed this default port ;) )

**Comment by diox** [comment]
The basic use-case is for websites allowing users to create account, which most of the time will only have one single login/password form on the whole website. That being said, IIRC, the following things are used for login / password autofill:
- hostname
- form submit URL
- the name/id of the login / password fields

Maybe there is some fuzzing mechanism going on to offer users logins from a different form is none is found, though, I don't know.

As for bug 956906, it made Firefox ignore autocomplete="off" for login/pass autocomplete because a lot of websites used that to prevent the password manager from working altogether, which is very bad for security (leads to worse passwords, passwords re-use, poor password storage, etc). That's a good thing :) A few other browsers do the same.

**Comment by diox** [comment]
BTW, the code for this in Firefox is in https://dxr.mozilla.org/mozilla-central/source/toolkit/components/passwordmgr
