### ISSUE TITLE
Add "browse by language" card in media center

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#242]

**Comment by barbayellow** [comment]
Maybe handling languages using the language switcher, in the mediacenter, or wherever, could be a better idea. I mean, each user has access to its own version of ideacube since people can acces to it using their devices. The language switcher should give access to a translated user interface and to the resources available in the same language. That would be a first step to personalize the user experience.

**Comment by yohanboniface** [comment]
Done through #335
