### ISSUE TITLE
Split conf files in a new Debian package?

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#284]
As of today, we have all the conf files (idb_jor_azraq.py and so on) bundled in to the ideascube git and Debian package.
We have made this choice, because we are remotely maintaining a bunch of servers and we want to be sure that configuration will upgrade when the code upgrade (if we had non versioned local configuration file we would end with issues on some server being upraded without knowing exactly what is the local config of those servers).

This though has two issues:
- we need to compile a new Debian package when doing a small change in conf file (like adding one conf file or just chaning say the default language of some other)
- those conf files are LWB specific, and we want ideascube to be as generic as possible

We are thinking about moving configuration files in a separate Debian package (let's call it ideascube-lwb, or maybe have two: ideascube-ideasbox and ideascube-koombook).

But we need a way for ideascube (installed through dh_virtualenv) to add ideascube-lwb into its pythonpath.
Plus we need a way to keep compatibility between ideascube and ideascube-lwb, possibly by keeping a strict dependency on the minor version.
Plus we need to build one more package on buildbot server.

**Comment by bochecha** [comment]
> But we need a way for ideascube (installed through dh_virtualenv) to add ideascube-lwb into its pythonpath.

We thought about that a bit today with @mgautierfr , and we were thinking we could just have a file `/etc/ideascube/settings.py`

The ideascube code would just try importing that file, instead of the current dance with the hostname.

And it would be ansiblecube's responsibility to take the right configuration file (e.g `idb_jor_azraq.py`) and install it as `/etc/ideascube/settings.py`.

This has the benefit of making things simpler, of having the configuration file managed by ansible (and as such to have folks like @letompouce and @fheslouin be able to change the configuration of a box without asking you to make a new release).

What do you think?

**Comment by yohanboniface** [comment]
> And it would be ansiblecube's responsibility to take the right configuration file (e.g idb_jor_azraq.py) and install it as /etc/ideascube/settings.py.

Where `idb_jor_azraq.py` would be versionned in this scenario?

**Comment by mgautierfr** [comment]
Config files would be versionned in another git repository (ideascube-lwb ?)

For the problem of keeping the code and the config in sync, a idea (to discuss) would be to have a config version number (used as a soname) that need to match:
- A "needed_version" is set in the ideascube code.
- The config file need to have a its version number > needed_version

When code evolves and changes the config "API", the needed_version is incremented. And so old config version is not valid anymore without update of the config files.
This is not perfect as versionning the config files with the code, but it let us separate the config files from the generic ideascube works.

**Comment by fheslouin** [comment]
I think having a separate repository is a nice idea. It will really help us in Ideasbox/KoomBook deployment. It would be a little bit more understandable for users that would like to try out ideascube. Still right now those config file are pretty hard to understand and to modify for a regular user.

@mgautierfr what I understood is something about an ideascube number needing a specific conf file version number.

The only thing we can not do is to change the file name...So everything has to be written in the file.

**Comment by bochecha** [comment]
So talking about that a bit more with @mgautierfr yesterday night, we figured maybe we could have a simpler scheme, without elaborate versioning checks.

How about this:

* Whenever a PR in **ideascube** changes something related to the settings (new option, new default value, change of semantics, removal of an option, ...), then we don't merge/release without an explicit ACK from at least one of the **ansiblecube** folks (i.e @letompouce or @fheslouin today, probably others in the future)

* The **ansiblecube** folks don't ACK these changes until ansiblecube is ready for the change

 1. For example if the change adds a new option, then @fheslouin would give his ACK once he has added the new option to all the existing configs. He can do that in advance, because the new option would be ignored if deployed on boxes before merging the ideascube change that adds/requires it.

 2. As another example, if the ideascube change removes an existing option, then @letompouce would give his ACK right away, because he shouldn't remove the option from the existing config files until **after** a machine has been updated to a newer ideascube, and leaving it in the config file would have no impact on the deployments (apart from future confusion, so it should be removed eventually, but there's no rush)

 3. And finally, if the adaptations in **ansiblecube** can't be done in advance, can't be done later on, but has to be done in coordination with the update to the new **ideascube** (for example, an existing setting pointing to a path starts being used for something else, and that requires moving files around on the boxes), then this requires further coordination and we'd only merge/release the ideascube change when @letompouce or @fheslouin are available and will be ready to change all the configs as they update the package on the deployed boxes. They could NACK the PR until such a time comes, and we (on the ideascube side) should refrain from ever doing any such change, unless it is absolutely necessary.

In effect, this comes down to treating the interface between the code and the settings as an ABI, without the whole soname/incompatibility dance, but instead favoring coordination, since overall we have a good track record of working together and not against each other. :smiley: 

This nicely avoids having to bump versions and checking for them, at the cost of a bit more discipline in the reviews, which seems perfectly acceptable to me, as an occasional coder/reviewer.

This also allows us to have only the `base` and `dev` configs in **ideascube**, and to let the **ansiblecube** folks manage their own configs wherever they want (probably another git repository in this github organization) and deploying them with ansiblecube in any way they want, without needing to beg for a new release.

It also means we don't need to make a new release each time we need a new config file for a new box. Those « empty updates » have a cost on the existing users, since they will download and install them even though they provide no benefit. They also have a cost on our build infrastructure, since we need to build new packages for what could be a simple ansible push.

---

What do you think? Does that sound like something we could make work? Do the benefits outweight the costs?

(my personal answer is "yes" on both questions)

**Comment by mgautierfr** [comment]
Yes @fheslouin, this is the idea : having a version number **in** the config file.
If the version number of the config file does not correspond to the one ideascube is waiting, we know that someone hasn't done its job correctly :)
About the version number itself, I imagine something really simple. Just a simple number.
When we change something relative to the config (add/remove setting, change semantics ...) we bump the required version number.

I agree with what @bochecha explain (well, we speak about it offline) but I partisan to still keep the idea of a version number. If we coordinate ourselves well, the version number is indeed not really necessary but gap in the coordination can appear (and will). Moreover, the goal of splitting the config is to let other people install ideascube on their own. They need a way to be sure their config files are up to date without having to closely follow the development and give us a ACK.

If we coordinate between us (dev) and **ansiblecube**, we can simply print a warning if config version doesn't match and still continue.

The drawback of this solution is that ansiblecube's folks have to update the config version number each time even if they change nothing else in the config.

**Comment by fheslouin** [comment]
I think we could have this king of process as long as we talk together when changes are made...It's kind of hard to figure out everything right now as I have not been there to talked about it offline.

What we should think of as well is how a regular user is going to create this file and how he/she is going to be able to configure Ideascube as his/her wish. 

Right now I think this is too complicated for someone new. How could we simplify this file ? How could we easily enable/disable cards ? 

I even make some mistake sometime because I'm forgetting a comma somewhere and Ideascube crash. Could we use for example a Yaml file instead ? It would maybe more easy to set up ?!

**Comment by mgautierfr** [comment]
I think the main thing to do to simplify the configuration of ideascube is to remove stuff from config file itself :smile: 

The cards for example could simply move out the configuration files and move in the database.
Then, the configuration of the cards will have to be done in the admin interface (the django one or a custom one).

The config file should be minimal and be about the admin stuff (ALLOWED_HOSTS, SECRET_KEY, ...)
Things relative to content (HOME_CARDS, other ?) should not be in the config file but be in the database (who already contains the content itself).

**Comment by letompouce** [comment]
Quick question: what would be the benefit of a debian package vs a git repository?

When we change the configuration of a single koombook:
- A debian package has to be built/compiled, then spread to all kb/idb
- a git repository will be git-pulled to all kb/idb

**Comment by bochecha** [comment]
> Quick question: what would be the benefit of a debian package vs a git repository?

None, you're entirely right.

I think that when @yohanboniface opened the ticket, we were thinking that having the configs in the main debian package was too annoying, therefore we should take it out, and as such the first idea that came to mind was to put it in a second package.

The discussion on this ticket shows that we seem to be more and more thinking about not putting the configurations in a package at all.
