### ISSUE TITLE
Do not automatically run migrate and collecstatic on Debian install

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#294]
Those two commands relies on local configuration (STORAGE_ROOT, STATIC_ROOT and so on) that are not configured by the user at install time.
The Debian convention is to use /etc/default/ideascube to configure it, but it's the Debian installer itself that adds it.

Of course, those two steps should then be added to the documentation.

I think we should still run `migrate` and `collectstatic` on update.

cc @bochecha I'd like your thoughts on this :)

**Comment by bochecha** [comment]
I've been thinking along the same line from the start, because in the Fedora world, installing a service does not start/enable it. Instead, the package is installed, has some default configuration, but it is left to the admin to run migrate-/collectstatic-style tasks and start/enable it.

But I never suggested it, because as far as I know, in the Debian world the convention is exactly the opposite: Debian folks consider that installing a service expresses a clear intent to have it started/enabled, therefore the service should come with a working configuration and all migrate-/collectstatic-style tasks run automatically.

Both make sense, I tend to prefer the first one, though, because it makes it easier to change stuff without having to repackage it, it avoids having a misconfigured service running for a short time before the admin has time to configure it, etc... (also, I'd be lying if I said I wasn't obviously biased in favor of what I've been doing for the past few years in my distro of choice :stuck_out_tongue_winking_eye: )

In any case, I'm entirely +1 to not running migrate/collectstatic any more on install. This could simplify dramatically our `postinst` script.

As for still running them on update, I'm not sure... Can we be sure that the admin had time to configure ideascube, and had already run migrate/collectstatic before the update? If they didn't, then is running those on update really different from running them on install?

I need to think a bit more about the update case, because I find it less clear-cut than the install case. :smiley:

**Comment by yohanboniface** [comment]
> As for still running them on update, I'm not sure... Can we be sure that the admin had time to configure ideascube, and had already run migrate/collectstatic before the update? If they didn't, then is running those on update really different from running them on install?

The difference I see, as for now, between install and update is that install will be done by tech people (mainly us for now but hey hopefully this will change :) ), while the update is supposed to be painless for any people able to manage a mouse.
Also, if the project is already running (has a db, is used, etc.), and someone run an apt update that pull in a db migration schema, but the `migrate` is not run, than the result will be a broken service.

One option *may* be to have a `smart_migrate` for the update: only run `migrate` if the db exists.

**Comment by bochecha** [comment]
> The difference I see, as for now, between install and update is that install will be done by tech people (mainly us for now but hey hopefully this will change :) ), while the update is supposed to be painless for any people able to manage a mouse.

That's a very good point, I forgot to consider that the goal was to make folks autonomous (as much as possible) on managing how the device runs, updates, etc...

So yeah, that definitely is a supporting argument towards running them on update.

> One option may be to have a smart_migrate for the update: only run migrate if the db exists.

I think it would be a good idea, but I'm not sure it's worth it.

---

I guess one more thing to consider about the migrate command is... can we guarantee that running migrate won't break the DB? (lose data, fail in the middle, etc...)

If there's a chance that it does, then we probably shouldn't run it automatically on package update, but instead let the admin run it manually, so that they have a chance to backup the db, and roll everything back if it comes to that.

Which now makes me think we probably should test database migrations from one version to another. How can we do that in the CI? :smile:

**Comment by bochecha** [comment]
I'm told by a Debian developer that we just shouldn't do that at all, neither on install nor on upgrade.

One problem is that if we run the `migrate` and `collectstatic` on upgrades and they fail, then the package manager transaction fails, the app is left in a half-done state, and...

What we could do instead is run the `migrate` and `collectstatic` when starting the application.

They are both no-ops if they don't need to do anything, so that wouldn't break anything, and it's relatively quick in the normal "just restart the app" scenario.

**Comment by yohanboniface** [comment]
> What we could do instead is run the migrate and collectstatic when starting the application.

Seems we'll also needs to have `reindex` in the process. cf https://github.com/ideascube/ideascube/pull/335#issuecomment-200853815
