### ISSUE TITLE
Media upload

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#328]
We should simplify the media upload process : 
- The type of the media should be automatically detected from the mime type
- Summary and credits should not be mandatory fields

Only the title should be mandatory.

**Comment by fheslouin** [comment]
+1

**Comment by yohanboniface** [comment]
> The type of the media should be automatically detected from the mime type

This is already the case, you can keep "other" and we will try to detect the type ;)
Do you mean removing totally the field from the form? Even in edit mode (for example if the autodetection of the type is bad)?
Damn, this make me think we have no autodetection for the "software" kind…

> Summary and credits should not be mandatory fields

No summary means no data to search on (but the title), but okay.
No credit is a bad habit, I'm against that change personnaly but will align on the consensus. ;)

**Comment by fheslouin** [comment]
After talking with some end users : 
- Credit should be explained as it is not really comprehensive for some people, could we have a little pop-up in order to explain that ? 
- Tags / Themes should be explain as well. Not all end users have been trained properly and we should state that nobody knows what is a tag and how it's work within the media-center. This is something really important to navigate through the content.
- The send button is placed on the right top of the form. Some people can't find it. It should be placed at the bottom of the form.
- Type can be confusing for some user that even don't know what could be a file type.
