### ISSUE TITLE
Yaml format must be versionned

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#347]
The catalog yaml format must be versionned especially for retro compatibility issues. We know this format will change in the coming month this is why we need this feature. The simplest way to do this would be to add a folder "/v0/" (then "/v1/" for the next version, then "/v2/" and so on) where the catalog file is stored.

**Comment by bochecha** [comment]
Discussing this a bit with @mgautierfr , we see two things which are important:

1. a client must be able to request a certain version of the API (e.g an old ideascube, not yet updated to the latest version, and as such not capable of handling newer versions of the catalog format)

The simplest way is to have the version of the format be part of the URL to the file, for example: https://catalog.ideascube.org/v1/catalog.yml

Since we currently serve catalog files as static file in a folder, we'd just move the current one to a versioned subfolder, and if we ever have some app with an api, then that would just continue working.

2. a way for clients to know what version they have downloaded.

The use case here is a machine running ideascube version X which only handles catalog format in its version 1. It has downloaded and cached the catalog file (list of available packages, etc...)

Then we upgrade that box to ideascube version Y, which now handles catalog format version 2. So it now downloads the catalog in its version 2, and it needs to know that it probably shouldn't merge it with its cached version 1, but just replace it entirely.

It would also be useful in various scripts when comparing catalog contents, etc.

A simple thing to do here is introduce a new top-level key in the YAML file (at the same level as the current `all` key, something like:

```yaml
meta:
  version: 1
all:
  ...
```

Since the current catalog parsing code just gets the `all` key, it would simply ignore this new `meta` one without any change to the code, until we're ready to start doing something with it.
