### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#348]
A few weeks ago, I changed unilaterally the license of the project from MIT to Affero GPL. This is not how it should have been done. Sorry for that. It is never too late to do the right thing. So let's vote : 

* thumbs up if if you agree with this change,
* thumbs down if you don't agree with this change,
* comment this issue to discuss license issues if you are thinking about something else than MIT or AGPL

**Comment by bochecha** [comment]
Here's the list of people who committed to ideascube, in order of their number of commits:

    572 @yohanboniface 
    118 @bochecha
     87 @fheslouin 
     34 @parmeso6
     27 @Geam
     25 @fheslouin 
      8 @benoitbryon
      7 @mariefontanel 
      7 @providenz
      6 @Dadouw 
      5 @barbayellow 
      4 @letompouce
      4 @mgautierfr 
      3 @endeav 
      3 @Duy22 
      2 @Natim 
      2 @mbaechler
      2 @dachary 
      1 @Yekpe 
      1 @utopman
      1 @leplatrem 
      1 @Lcaracol
      1 @gawel 
      1 @chrisglass

So theoretically, we should get authorization from all these people.

Note that relicensing from MIT to AGPL is perfectly legal, you do not need anybody's permission. It is however not super nice, and asking for permission is better form. (but then it might mean still doing it and going against people's will)

**Comment by bochecha** [comment]
I'm :+1: to this change.

In fact, I'm very happy to move from MIT to AGPL. :smile:

**Comment by dachary** [comment]
:+1:

**Comment by mgautierfr** [comment]
:+1:

**Comment by chrisglass** [comment]
+1, it's a tiny commit anyway :)
On May 28, 2016 23:15, "Matthieu Gautier" <notifications@github.com> wrote:

👍

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ideascube/ideascube/issues/348#issuecomment-222330035>,
or mute the thread
<https://github.com/notifications/unsubscribe/AABie9nEpo29d27JfzyTNXjZVI42jsMnks5qGLB7gaJpZM4IpCsS>
.

**Comment by mbaechler** [comment]
I don't really have meaningful contributions anyway, feel free to choose the license that fits your needs. 👍

**Comment by utopman** [comment]
Same for me, so I'm ok with thiw change

**Comment by Natim** [comment]
Can you elaborate on the rationale behind this change?

I prefer when you can contribute what you want rather than to force people
to contribute everything around a project.

Most of the time everything doesn't make sense and it can block innovation.

For instance does it means that if you add a new template theme it must be
open-source too?

For this project I don't really mind but agpl is probably too restrictive
when you seek for cross companies collaboration.

**Comment by bochecha** [comment]
> I prefer when you can contribute what you want rather than to force people to contribute everything around a project.

This is a (unfortunately common) misconception. The *GPL licenses do not force you to contribute your code back to the upstream project.

They only force you to agree to distribute the sources **to the users you distributed the product to**. (and in the case of the AGPL, the definition of "user" is a bit larger than it is for the GPL)

http://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html#GPLRequireSourcePostedPublic

> For instance does it means that if you add a new template theme it must be open-source too?

If Ideascube is AGPL, then it means you must distribute your new template theme under the AGPL **to the people who use your instance of ideascube**. Of course, it means you can't prevent them from then redistributing it as they please, but you are under no obligation to do it yourself.

**Comment by barbayellow** [comment]
@Natim IMHO changing the license is a **statement**. Since this project is about knowledge sharing, I think that the aim of the software should be reflected in its license. I do understand the worries that a less permissive license could slow down innovation. However some very successful project have been using and are still using a GPL.

**Comment by Natim** [comment]
Thanks you Mathieu for the clarification. If it sounds reasonable to you
then let's do it :)

**Comment by leplatrem** [comment]
I've got nothing against the change either!

**Comment by fheslouin** [comment]
Go :+1:

**Comment by yohanboniface** [comment]
LGTM

**Comment by endeav** [comment]
👍

**Comment by parmeso6** [comment]
👍

**Comment by Lcaracol** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Pa ni pwoblem
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.11 (GNU/Linux)

iEYEARECAAYFAldMRwgACgkQBIYZ6zNww76mIgCffmeylAJ1ME+gQH2HmCl1qnfO
yEkAnjeKMVrmxj0aYSvNcdZbzLm8G4HZ
=a+Xp
-----END PGP SIGNATURE-----

**Comment by letompouce** [comment]
WTFPL doesn't seem to be an available option, yet it illustrates my opinion :D

**Comment by letompouce** [comment]
I was told my statement wasn't clear, true true...

My opinion on this issue is, 👍 DO WTF YOU WANT with the licence change.

**Comment by bochecha** [comment]
I cooked up a quick script that gets stats over the ideascube codebase and who did/didn't agree to relicense to AGPL.

Here's the result:

```
Author stats
------------

Approval covers:         15 authors       (65.22% of total)
Refusal covers:           0 authors       ( 0.00% of total)
Missing response for:     8 authors       (34.78% of total)

Commit stats
------------

Approval covers:        872 commits       (93.56% of total)
Refusal covers:           0 commits       ( 0.00% of total)
Missing response for:    60 commits       ( 6.44% of total)

Current line stats
------------------

Approval covers:      40321 current lines (99.00% of total)
Refusal covers:           0 current lines ( 0.00% of total)
Missing response for:   409 current lines ( 1.00% of total)
```

So even if we got approval from only ~65% of the people who have at one point contributed to ideascube, that covers ~93% of all the commits in the history of the project.

And if we look only at the current lines of code in a checkout from master, then the approval we got covers about ~99%.

To me this shows we pretty much have a consensus in favour of the change among the contributors who did most of the work and are still actively contributing.

Since the license change was legal anyway, maybe it's time to enact it and close this issue? :smiley:

**Comment by barbayellow** [comment]
agreed !
