### ISSUE TITLE
Embeded medias in videos

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#365]
The feature "embed a media" is not working. In the content field, once I have clicked on the "embed a media icon", and once I have entered the url from a video from the mediacenter, nothing happen. Is there something I have missed ?

This feature _could be used_ in the Grande Synthe project (hopefully).

**Comment by yohanboniface** [comment]
You need to paste the media URL (i.e. the URL for the browser when your are viewing the media page), not the video URL.

**Comment by yohanboniface** [comment]
To make it a bit clearer, the URL you'll paste into the input should like something like http://ideasbox.lan/en/mediacenter/document/4/

**Comment by barbayellow** [comment]
Understood.  However, is it possible to include directly a media from the 
blog application or should we always upload it in the mediacenter first ?

**Comment by yohanboniface** [comment]
> should we always upload it in the mediacenter first ?

It must be in the mediacenter first. I don't think we want the other option, because that would be creating another mediacenter just for the blog (because you need to manage uploads, you need to be able to search for the already uploaded content, etc.).
The improvement direction is certainly to make it easier to upload a media in the mediacenter from within the blog, and to be able to browse medias from within the "add media" box.

Closing here because that's anyway another topic.
