### ISSUE TITLE
Impossible to add more than 2 emeded medias in a blog post

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#367]
Trying to add more than one embeded media in a blogpost is impossible. After the blog post is saved, only one media is displayed.

**Comment by yohanboniface** [comment]
Reproduced! I'll try to have a look today.

**Comment by yohanboniface** [comment]
So, what's happening is:

- adding a media adds a <div> element, containing both the media tag (img…) and the caption.
- when putting the cursor after the caption and hitting the enter key, the new paragraph (<p>) is created **inside** the media <div>

That needs to be fixed in minislate third-party JS lib we are using (but it's not maintained any more :s ).

Not sure how to deal with this the clean way.

**Comment by yohanboniface** [comment]
I think the pattern should be something like:
- when ENTER is pressed,
- find the display=block element parent of the cursor position AND immediately child of the main editable element
- add the new paragraph after this parent block

**Comment by yohanboniface** [comment]
BTW, workaround is to take care always inserting media before some text. So we can create a new paragraph after this text to insert a new media. Or inserting the new media *before* an already inserted media.
