### ISSUE TITLE
Change default ideascube conf file

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#373]
Currently the default file used by ideascube is the conf.dev file which in between set CATALOG_CACHE_BASE_DIR to '/var/ideascube'

Afterward, the catalog command store the data in /var/cache/ideascube/.

We should clean up this and set a demo conf instead with the right settings...

**Comment by yohanboniface** [comment]
Note: I think we should keep the default as is when running from manage.py, but have a more generic conf when running from uwsgi.

**Comment by bochecha** [comment]
So the `dev.py` config sets things this way, because it is intended (as the name suggests) for developers.

Developers run ideascube under their own user, from a git clone, and as such they don't have `/var/cache/ideascube` ready.

That is why, for developers, we set `CATALOG_CACHE_BASE_DIR` to `os.path.join(STORAGE_ROOT, 'catalog')`, that is to `./storage/catalog`, relative to the git clone.

On the other hand, for deployments, we set `CATALOG_CACHE_BASE_DIR` to `/var/cache/ideascube/catalog` in `base.py`, so that all deployments have it there.

So... what's the problem? :smile:

**Comment by yohanboniface** [comment]
> So... what's the problem?

If you install the package without any conf file being found, so `dev.py` will be loaded, and then…

What we want is to default to something else than `dev.py` (maybe nothing more than `base.py`) when running from a package (i.e. not from manage.py).

**Comment by yohanboniface** [comment]
The option may be as simple as having `manage.py` to set default `IDEASCUBE_ID` environ value to `dev`.
