### ISSUE TITLE
Mute videos

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#377]
We have some mute cartoons in the medias. We can't associate any language to it. We should be able to add this information in the language field. something like "Mute" or "no language" .

**Comment by bochecha** [comment]
Or something like a "*" wildcard?

The language tag is IMHO meant to describe the languages of **people** you want to present the video to, not the languages actually spoken in the video.

The difference is subtle, but a video in French could have the `fr_CA` and `fr_FR` languages, even though people in the video are from France.

And if you look at it in this way, then a mute video is not a video without languages... it's a video you might want to present to everybody, no matter what their language is!

As a result, something that means "all languages" feels more appropriate than something that means "no language".

Hence the "*" wildcard. :smile:

**Comment by barbayellow** [comment]
Wildcard is a good idea. But maybe we should translate it for human. this is why the "all languages" or "no languages" is something that could be more understandable. Except for non English speakers.

**Comment by bochecha** [comment]
Right, so of course both a computer-friendly and human-friendly version are needed.

Just like "fr_FR" is more useful to computers than "Français", "*" is more useful to computers than "All languages".

I thought you were talking about the tag to write inside the catalog to describe the content package, which is why I went with a computer-friendly value.

If you meant something else, then ignore me. :)

**Comment by barbayellow** [comment]
I did not have this in mind, but it's important though. So let's say 
-  "*" for the catalog
- "All languages" translated in every supported language, for the human
