### ISSUE TITLE
Do not create a Nginx VHost for static-site packages

### ISSUE THREAD

**Issue by letompouce** [ideascube/ideascube#431]
When installing a static-site package, such as `world.map`, ideascube tries to install a vhost in nginx, such as `world.map.ideasbox.lan`.

Chicken and egg issue: as root, the content might not be accessible by the ideascube user ; as ideascube, no write access shall be granted to `/etc/nginx/`.

Let's kill the egg and the chicken altogether: don't create a vhost for every package, but rather make the static-site contents accessible from a generic vhost. The `server_name` would look like `static-sites.ideasbox.lan/world.map/`, and its `root` would be `/var/ideascube/nginx/lebanon.map`.

This also would be consistent with the URI pattern we use for Kiwix contents, such as `kiwix.ideasbox.lan/wikipedia.en/`.

Biggest issue now is to find a good name for this FQDN :D

**Comment by yohanboniface** [comment]
♥

As for the domain, I suggest "static.ideascube/koombook.lan", or "static-site.", given that this is the type of package used in this case.
Small issue: what to do for backward compatibility.
We *may* answer nothing, given that for now every update will be handcrafted AFAIK.

**Comment by bochecha** [comment]
I'd say `sites.ideasbox.lan`. Naming it after the package type seems suboptimal, as package types are an implementation detail and URLs are very much visible (even though they are not the primary means of getting to the site, since people will instead click on the card) in the web browser.

« static » is also an implementation detail: it doesn't matter much to visitors of a website whether it is static or built with a dynamic CMS, they just visit a (web) site.

Other than that, this is awesome, and fixes a very real issue, kudos for the solution @letompouce .

**Comment by letompouce** [comment]
> I'd say sites.ideasbox.lan. Naming it after the package type seems suboptimal, as package types are an implementation detail and URLs are very much visible

<3

**Comment by yohanboniface** [comment]
@fheslouin would you have time to handle that on the ansible side this week by chance? That means creating a new generic VHost (something like sites.ideasbox/koombook.lan), and a migration to remove the old VHosts.
I'd love to clean that process badly designed (by me), and I can work on the ideascube side.
