### ISSUE TITLE
Update KoomBook battery page

### ISSUE THREAD

**Issue by fheslouin** [ideascube/ideascube#446]
Can we update the battery info page for the KoomBook
- Power connected or disctonnected 
  - `/sys/power/axp_pmu/ac/connected` (Return 0 or 1)
- Battery charging or not 
  - `/sys/power/axp_pmu/battery/charging` (Return 0 or 1)
- Battery connected to the board 
  - `/sys/power/axp_pmu/battery/connected`  (Return 0 or 1)
- Battery capacity 
  - `/sys/power/axp_pmu/battery/capacity` (in %)

We can get info from the battery charger as well, it can be interesting for admin purpose : 
- Power Management Unit Voltage :
  - `/sys/power/axp_pmu/pmu/voltage` (in Volt)
- Power Management Unit temperature :
  - `/sys/power/axp_pmu/pmu/temp` (in °C)

**Comment by bochecha** [comment]
The problem with this is that we'd be displaying that the battery is e.g 60% full.

An admin with this page open would think « nice, lots of time left ».

Fast forward a couple of hours, the page still says 60%, but the battery has obviously been drained some.

However, the admin won't see that until they refresh the page.

So we'd need the info on the page to refresh automatically, preferably asynchonously.

Enter upower and cockpit. (the latter of which I'm already planning on using to redo the wifi management)

**Comment by fheslouin** [comment]
Automatic refresh is a nice feature, but I don't know when this will be available. 

I think what urge right now is having a rough idea of how much battery I get for the next hour...If we can implement automatic refresh this is even better but this can come later on.

**Comment by yohanboniface** [comment]
Agreed that the info should update itself, AND that we need to move in two steps: fix the actual battery page first, have an auto update later.

**Comment by bochecha** [comment]
Ok, so I investigated this a bit.

The `batinfo` module we use searches for batteries in sysfs, under the `/sys/class/power_supply/` path.

And that seems to be [the standard sysfs interface for batteries on Linux](https://www.kernel.org/doc/Documentation/power/power_supply_class.txt).

And as such, the battery page in ideascube works just fine on my laptop. :smile: 

The problem is that the hardware we use for Koombooks is a bit exotic. It depends on the axp20x driver which does things differently, with its own paths, because... well I have no idea why. :smile: 

That driver seems to exist in the mainline kernel, but that doesn't seem to be the version we are using.

Instead, what we're using seems to have been patched with, among other things, [this](https://github.com/igorpecovnik/lib/blob/master/patch/kernel/sunxi-next/axp20x-sysfs-interface.patch)

This patch is what adds the sysfs stuff with the seemingly incorrect paths. The patch doesn't seem to contain any explanation, though. :(
