### ISSUE TITLE
Weird button in the top bar of kiwix content

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#448]
when browsing content from a zim file using kiwix, for instance http://kiwix.demo.ideascube.lan/vikidia.en/, a top bar is automatically added. It contains a search field and 3 buttons : 
- library
- home
- random

The home button links to the home of the zim file -> cool
The random button leads to a random page -> cool
The library button leads to the list of all the zim files -> weird

Is there a way to remove the library button from the top bar ? A setting in kiwix for instance ?

![selection_007](https://cloud.githubusercontent.com/assets/4816690/17963057/fe8d0f04-6ab3-11e6-88ce-e5cb7b8cb7bf.jpg)

**Comment by yohanboniface** [comment]
@mgautierfr any sort of idea how we can deal with that in the future?
Adding it to the backlog so we can discuss it next meeting.

**Comment by mgautierfr** [comment]
A first try has been made here : https://github.com/ideascube/ideascube/pull/590

The idea behind this PR is to have a custom proxy page that embed the kiwix page into the iframe.
The kiwix-serve itself do not show the topbar but the proxy page does it itself.
It seems that it was a good idea but I end fighting myself with cross-origin authorization, url rewriting in js and such other no funny things.

@bochecha wisely hints me that the proxy was maybe not a good idea and I have reoriented the work on kiwix-serve itself.

The next version of kiwix-serve, will allow a user to override the content inserted in the page for the topbar throw a environment variable. This way, with the right template, we can use our own topbar.
And guess what, I've have the right template :)

![wikiquote_top](https://cloud.githubusercontent.com/assets/86161/21459701/e3b4445e-c940-11e6-8348-957356c6c430.png)
![wikiquote_middle](https://cloud.githubusercontent.com/assets/86161/21459702/e3b4a0d4-c940-11e6-9c1a-c44ca2ac48f1.png)


I globally works but this is not perfect :

![wikipedia_ar](https://cloud.githubusercontent.com/assets/86161/21459700/e3b2abf8-c940-11e6-9ae3-bb356ace6a67.png)

As the inserted template is a static file in the fs, we cannot add a lot a customization depending of the
content (ltr or rtl, i18n, ...) (but it was already the case before)

Pros :
 - Almost no change on ideascube
 - We just have to place a static file for the html template and the css somewhere and configure
kiwix-serve to use them at launch in ansiblecube.
- No url change

Cons:
- The inserted template is in the same context that the content. So a page could use CSS rules we don't think about and break our styling. (That's why the content is inverted in the top bar, a rtl rules somewhere in the CSS)
 - That's static content. It was the same before, but the proxy version was served by ideascube so,
we could do so customization (even if I haven't done it)
- Extra content (as font) have to served by someone else.
- We have several content relatively coupled (styling, font, ...) spread in two different places.

Here is the template itself :

[taskbar.html.txt](https://github.com/ideascube/ideascube/files/671256/taskbar.html.txt)


And before you ask:
 - Yes, we use jquery. It is for the autocomplete functionnality. It's come from the kiwix-serve version of the topbar and yes jquery is "simply" embedded in kiwix-serve itself.
 - I a css served by ideascube cause it was simpler to develop with the try and fail method :)

**Comment by barbayellow** [comment]
This is something that wil help to bring more consistency in ideascube. So I really think this is a needed PR! The only pb is since it is a static file, we won't be able to add the name of the server in the top bar, since this name comes from ideascube. But I guess there are some workarounds. 

On a second thought, maybe this not a big pb not to have all the info we have on the home page in the kiwix apps. So we could just have a logo and a search bar. However, if we do this, to keep a consistant design, we would have to change the search bar in the media center aswell in order to have the same search bar everywhere.
