### ISSUE TITLE
User import/export

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#485]
We should be able to import users by batch in ideascube. This is what our Colombian partner is asking. Attached is a sample csv from their app.

Once imported, we should be able to export the information created around the users by the box managers, meaning : 
- user qualification
- user activity (from the entries app)

[Usuarios.txt](https://github.com/ideascube/ideascube/files/470816/Usuarios.txt)

**Comment by yohanboniface** [comment]
> Attached

Missing ;)

We already have a users export, I'd rather have our partner use this same format, so we do not deal with specificities partner by partner. At the end it's all about column naming and values conventions (language, etc.).

**Comment by barbayellow** [comment]
agreed!

**Comment by yohanboniface** [comment]
We agreed with the partner that they will produce a CSV with ideascube format (column names and values).
On our side we need to add the import, that should import whatever column in the CSV which name is a ideascube User fields.
Of course, only valid data should be imported (using UserForm), and `serial` is the only mandatory field.
Skip rows with invalid data, but continue importing other rows, and display one error message for each row with errors (but say max 10 messages).

**Comment by yohanboniface** [comment]
I can perceive some issues around the corner. Now that we will be able to import users, we'll have cases where we'll want to reimport user data we exported ourselves (being another server or the same server, as a backup.
Here we have at least two issues:
- USER_PRIVATE_DATA is filtering out some fields
- the column name in the exported CSV are the verbose names of the field (translated in the active language), not the field names

That is certainly not a blocking issue for the current iteration (because the data we'll import is coming from Llave del saber), but it's right next door.
