### ISSUE TITLE
home_page: add a checkbox to click 'em all

### ISSUE THREAD

**Issue by letompouce** [ideascube/ideascube#536]
After ZIMs have been installed, one has to go to `/server/home_page` and select all the cards. As a lazy operator, I wish I could click some 'All' button/checkbox/thing.

**Comment by bochecha** [comment]
I'm not debating the need for this feature.

However...

> After ZIMs have been installed, one has to go to /server/home_page and select all the cards.

Normally, after installing zims they automatically get added to the home. Is that not what you're seeing?

**Comment by letompouce** [comment]
The ansiblecube playbook installs ideascube, then installs the ZIMs.

Not sure about what happened in which order ; the server was installed with ansiblecube and ideascube pinned to 0.12.2, then upgraded to 0.13.0, and at this point there was only the Khan academy card on the home page. I had to go and click'em all.

**Comment by bochecha** [comment]
Right, the zims get automatically added to the home if they are installed with ideascube >= 0.13.0

That's why you had to click them all: you upgraded to ideascube 0.13.0 **after** installing all the zims.

Note that I'm working **right now** on something to fix this very case of upgrades losing the cards.
