### ISSUE TITLE
Import with ISBN should import book cover

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#565]
In the library app, one can import books from openlibrary.org using ISBN. It works when the book is available in openlibrary, however, the cover is not imported. 
If you want to try, here is an example of a book with an ISBN and a cover : https://openlibrary.org/works/OL9916058W/Exercices_d'oral_en_contexte_niveau_d%C3%A9butant

**Comment by yohanboniface** [comment]
This used to work, so that sounds like a bug. Their format may have changed.
Here is the relevant code if someone wants to take it during the sprint: https://github.com/ideascube/ideascube/blob/master/ideascube/library/utils.py#L47
Should be quite easy (a matter of changing where we look for the cover is the data, and updating the unittests accordingly).

**Comment by bochecha** [comment]
It could be that they changed the data they return us, or it could be that I broke it with the recent change related to the library and stock. :disappointed:
