### ISSUE TITLE
add User.disability

### ISSUE THREAD

**Issue by yohanboniface** [ideascube/ideascube#608]
Possible values:
- visual
- auditive
- physical
- cognitive
- mental

Of course the field is nullable, and null by default.
Needed for Colombian project.

**Comment by yohanboniface** [comment]
@barbayellow I'm assigning you this issue, that needs a bit of arbitration.
Basically, we need to decide:
- wheither to have a fixed list of values or a free text field
- if fixed list, decide which values to use

See https://github.com/ideascube/ideascube/pull/617

**Comment by barbayellow** [comment]
- Fixed values seems better to me, especially because we'd like to have  as much homogeneity as possible amongst all the mobile libraries and LWB projects.
- regarding the list it seems quite exhaustive to me. We could add the joker "other" to be sure to cover every case and not to have to modify this list later.
