### ISSUE TITLE
Docs aren't built any more

### ISSUE THREAD

**Issue by bochecha** [ideascube/ideascube#673]
It seems Read The Docs doesn't build our docs any more.

Last build was on Jan 2016, but we've made changes to the docs since then which should have been picked up:

http://readthedocs.org/projects/ideascube/builds/

**Comment by bochecha** [comment]
Turns out I could actually start a build, without even having an account on Read The Docs. 😮

**Comment by yohanboniface** [comment]
Any RTFD user in the team I can give admin rights to?

**Comment by bochecha** [comment]
I'm `bochecha` on RTD, and @mgautierfr is `mgautierfr`.

**Comment by mgautierfr** [comment]
I don't see why the docs were not built, it seems that the rebuild is just not triggered by github.
I reinstall the webhook on github. Manually triggering the webhook correctly launch the readthedoc build.
Maybe it was a bug on the github/readthedoc sides. I will watch next merges to be sure that everything is ok.

I also force the use of Python3 on readthedocs side to handle #679 (but it is really recent, so that not the original problem).
