### ISSUE TITLE
Removing medias from media center does not erase the file one the dd

### ISSUE THREAD

**Issue by barbayellow** [ideascube/ideascube#684]
When removing a media from the media center, the file is not removed from the hard drive. This is a problem since we have storage issues, especially with the koombook.

**Comment by barbayellow** [comment]
I'm runing ieascube 0.22. I removed a media from the mediacenter and it is still  in the file system in /var/ideascube/main/media/mediacenter/document even after a restart, when the file was an orphean.

`
'pi@barbabook-939:/var/ideascube/main/media/mediacenter/document $ ls
17_Everybody_Knows.mp3  orange-edupi-open.png  Volume-1-Eb.pdf  Volume-2-Eb.pdf.png
pi@barbabook-939:/var/ideascube/main/media/mediacenter/document $ rm 17_Everybody_Knows.mp3 
rm: remove write-protected regular file ‘17_Everybody_Knows.mp3’? yes
rm: cannot remove ‘17_Everybody_Knows.mp3’: Permission denied
pi@barbabook-939:/var/ideascube/main/media/mediacenter/adocument $ sudo rm 17_Everybody_Knows.mp3'`

  thus I am reopoening the issue.

**Comment by bochecha** [comment]
> I'm runing ieascube 0.22. I removed a media from the mediacenter and it is still in the file system in /var/ideascube/main/media/mediacenter/document even after a restart, when the file was an orphean.

Right, so the way we ended up implementing this is with an external command you need to run:

```
$ ideascube clean leftover-files [--dry-run]
```

We did it this way for a few reasons.

First, it handles leftover files for both deleted and updated medias. We could have done that directly in the app, however that required some trickery with the Django ORM and form layers, transactions, ...

But even if we had done it automatically, we still would have needed a command to clean the leftover files for medias that had been deleted in the past, with older versions of Ideascube.

As a result, we found it simpler to only have the command, and just run it regularly (with a cron job or systemd timer) on the boxes.

Right now Ansiblecube will set up a systemd timer to run the command and periodically clean the leftover files (10 minutes after bootup, then every week if the machine stayed up for that long).

Eventually we were thinking about moving this to the Ideascube package, so that it's done as well for deployments not using Ansiblecube, but we didn't get there so far.
